name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node Check
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm ci || exit 1

      - name: Prisma Generate
        run: npx prisma generate || exit 1

      - name: Build
        run: npm run build || exit 1

      - name: Prepare Deployment Package
        run: |
          mkdir -p deploy
          cp -r dist prisma package.json package-lock.json tsconfig.json deploy/
          tar -czf deploy.tar.gz -C deploy .

      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key deploy.tar.gz ${USER}@${HOST}:~/
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            mkdir -p ~/stepmerrily
            tar -xzf deploy.tar.gz -C ~/stepmerrily
            cd ~/stepmerrily
            npm ci
            npx prisma generate
            pm2 restart main' || exit 1
          rm -f private_key
